FROM python:3.8.0-buster

LABEL org.opencontainers.image.title="Flask"

Add main.py .

#Info: Copy requirements, needs two args file and destination
copy requirements.txt .
#Info: Install dependencies
pip install -r requirements.txt

cmd ["python", "./main.py"]